import type { AdminOrder, AdminCustomer, SalesData } from "@/types/admin";
import { MOCK_PRODUCTS } from "./mockData";

// ─── Mock Orders ─────────────────────────────────────────
export const MOCK_ORDERS: AdminOrder[] = [
  {
    id: "ORD-2026-0001",
    customerName: "Ahmed Hassan",
    customerEmail: "ahmed.hassan@gmail.com",
    customerPhone: "+20 100 123 4567",
    products: [
      {
        productId: "1",
        name: MOCK_PRODUCTS[0].name,
        image: MOCK_PRODUCTS[0].images[0],
        price: MOCK_PRODUCTS[0].price,
        quantity: 1,
        size: 42,
      },
      {
        productId: "5",
        name: MOCK_PRODUCTS[4].name,
        image: MOCK_PRODUCTS[4].images[0],
        price: MOCK_PRODUCTS[4].price,
        quantity: 1,
        size: 43,
      },
    ],
    total: MOCK_PRODUCTS[0].price + MOCK_PRODUCTS[4].price,
    orderStatus: "New Order",
    paymentStatus: "Paid",
    shippingStatus: "Pending",
    shippingAddress: "15 Tahrir Square, Cairo, Egypt",
    date: new Date().toISOString(),
  },
  {
    id: "ORD-2026-0002",
    customerName: "Mohamed Ali",
    customerEmail: "m.ali@outlook.com",
    customerPhone: "+20 111 234 5678",
    products: [
      {
        productId: "2",
        name: MOCK_PRODUCTS[1].name,
        image: MOCK_PRODUCTS[1].images[0],
        price: MOCK_PRODUCTS[1].price,
        quantity: 2,
        size: 41,
      },
    ],
    total: MOCK_PRODUCTS[1].price * 2,
    orderStatus: "Contacted",
    paymentStatus: "Paid",
    shippingStatus: "Pending",
    shippingAddress: "22 Corniche El Nil, Giza, Egypt",
    date: new Date().toISOString(),
  },
  {
    id: "ORD-2026-0003",
    customerName: "Sara Youssef",
    customerEmail: "sara.y@gmail.com",
    customerPhone: "+20 122 345 6789",
    products: [
      {
        productId: "7",
        name: MOCK_PRODUCTS[6].name,
        image: MOCK_PRODUCTS[6].images[0],
        price: MOCK_PRODUCTS[6].price,
        quantity: 1,
        size: 39,
      },
    ],
    total: MOCK_PRODUCTS[6].price,
    orderStatus: "Confirmed",
    paymentStatus: "Paid",
    shippingStatus: "Pending",
    shippingAddress: "7 Manial Street, Cairo, Egypt",
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "ORD-2026-0004",
    customerName: "Omar Khaled",
    customerEmail: "omar.k@yahoo.com",
    customerPhone: "+20 100 456 7890",
    products: [
      {
        productId: "3",
        name: MOCK_PRODUCTS[2].name,
        image: MOCK_PRODUCTS[2].images[0],
        price: MOCK_PRODUCTS[2].price,
        quantity: 1,
        size: 44,
      },
      {
        productId: "9",
        name: MOCK_PRODUCTS[8].name,
        image: MOCK_PRODUCTS[8].images[0],
        price: MOCK_PRODUCTS[8].price,
        quantity: 1,
        size: 44,
      },
    ],
    total: MOCK_PRODUCTS[2].price + MOCK_PRODUCTS[8].price,
    orderStatus: "Packed",
    paymentStatus: "Paid",
    shippingStatus: "Pending",
    shippingAddress: "3 Al Haram Road, Giza, Egypt",
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "ORD-2026-0005",
    customerName: "Nour Ibrahim",
    customerEmail: "nour.ibrahim@gmail.com",
    customerPhone: "+20 115 567 8901",
    products: [
      {
        productId: "5",
        name: MOCK_PRODUCTS[4].name,
        image: MOCK_PRODUCTS[4].images[0],
        price: MOCK_PRODUCTS[4].price,
        quantity: 1,
        size: 40,
      },
    ],
    total: MOCK_PRODUCTS[4].price,
    orderStatus: "Shipped",
    paymentStatus: "Paid",
    shippingStatus: "In Transit",
    shippingAddress: "9 Nasr City, Cairo, Egypt",
    trackingNumber: "TRK-EG-20260001",
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "ORD-2026-0006",
    customerName: "Youssef Mahmoud",
    customerEmail: "y.mahmoud@gmail.com",
    customerPhone: "+20 101 678 9012",
    products: [
      {
        productId: "6",
        name: MOCK_PRODUCTS[5].name,
        image: MOCK_PRODUCTS[5].images[0],
        price: MOCK_PRODUCTS[5].price,
        quantity: 1,
        size: 42,
      },
    ],
    total: MOCK_PRODUCTS[5].price,
    orderStatus: "Out For Delivery",
    paymentStatus: "Paid",
    shippingStatus: "In Transit",
    shippingAddress: "55 Heliopolis, Cairo, Egypt",
    trackingNumber: "TRK-EG-20260002",
    date: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "ORD-2026-0007",
    customerName: "Layla Adel",
    customerEmail: "layla.adel@hotmail.com",
    customerPhone: "+20 122 789 0123",
    products: [
      {
        productId: "12",
        name: MOCK_PRODUCTS[11].name,
        image: MOCK_PRODUCTS[11].images[0],
        price: MOCK_PRODUCTS[11].price,
        quantity: 1,
        size: 38,
      },
    ],
    total: MOCK_PRODUCTS[11].price,
    orderStatus: "Delivered",
    paymentStatus: "Paid",
    shippingStatus: "Delivered",
    shippingAddress: "12 Maadi, Cairo, Egypt",
    trackingNumber: "TRK-EG-20260003",
    date: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "ORD-2026-0008",
    customerName: "Karim Samir",
    customerEmail: "karim.s@gmail.com",
    customerPhone: "+20 100 890 1234",
    products: [
      {
        productId: "4",
        name: MOCK_PRODUCTS[3].name,
        image: MOCK_PRODUCTS[3].images[0],
        price: MOCK_PRODUCTS[3].price,
        quantity: 1,
        size: 43,
      },
    ],
    total: MOCK_PRODUCTS[3].price,
    orderStatus: "Cancelled",
    paymentStatus: "Refunded",
    shippingStatus: "Failed",
    shippingAddress: "88 Dokki, Giza, Egypt",
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
    notes: "Customer requested cancellation",
  },
  {
    id: "ORD-2026-0009",
    customerName: "Hana Mostafa",
    customerEmail: "hana.m@gmail.com",
    customerPhone: "+20 111 901 2345",
    products: [
      {
        productId: "8",
        name: MOCK_PRODUCTS[7].name,
        image: MOCK_PRODUCTS[7].images[0],
        price: MOCK_PRODUCTS[7].price,
        quantity: 2,
        size: 40,
      },
    ],
    total: MOCK_PRODUCTS[7].price * 2,
    orderStatus: "Delivered",
    paymentStatus: "Paid",
    shippingStatus: "Delivered",
    shippingAddress: "34 Zamalek, Cairo, Egypt",
    trackingNumber: "TRK-EG-20260004",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "ORD-2026-0010",
    customerName: "Tarek Nabil",
    customerEmail: "tarek.n@yahoo.com",
    customerPhone: "+20 100 012 3456",
    products: [
      {
        productId: "10",
        name: MOCK_PRODUCTS[9].name,
        image: MOCK_PRODUCTS[9].images[0],
        price: MOCK_PRODUCTS[9].price,
        quantity: 1,
        size: 45,
      },
      {
        productId: "11",
        name: MOCK_PRODUCTS[10].name,
        image: MOCK_PRODUCTS[10].images[0],
        price: MOCK_PRODUCTS[10].price,
        quantity: 1,
        size: 45,
      },
    ],
    total: MOCK_PRODUCTS[9].price + MOCK_PRODUCTS[10].price,
    orderStatus: "New Order",
    paymentStatus: "Pending",
    shippingStatus: "Pending",
    shippingAddress: "67 Shubra, Cairo, Egypt",
    date: new Date().toISOString(),
  },
];

// ─── Mock Customers ──────────────────────────────────────
export const MOCK_CUSTOMERS: AdminCustomer[] = [
  {
    id: "CUS-001",
    name: "Ahmed Hassan",
    email: "ahmed.hassan@gmail.com",
    phone: "+20 100 123 4567",
    totalSpent: MOCK_PRODUCTS[0].price + MOCK_PRODUCTS[4].price,
    totalOrders: 1,
    lastPurchase: new Date().toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 30).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-002",
    name: "Mohamed Ali",
    email: "m.ali@outlook.com",
    phone: "+20 111 234 5678",
    totalSpent: MOCK_PRODUCTS[1].price * 2,
    totalOrders: 3,
    lastPurchase: new Date().toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 60).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-003",
    name: "Sara Youssef",
    email: "sara.y@gmail.com",
    phone: "+20 122 345 6789",
    totalSpent: MOCK_PRODUCTS[6].price,
    totalOrders: 1,
    lastPurchase: new Date(Date.now() - 86400000).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 15).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-004",
    name: "Omar Khaled",
    email: "omar.k@yahoo.com",
    phone: "+20 100 456 7890",
    totalSpent: MOCK_PRODUCTS[2].price + MOCK_PRODUCTS[8].price,
    totalOrders: 2,
    lastPurchase: new Date(Date.now() - 86400000 * 2).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 45).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-005",
    name: "Nour Ibrahim",
    email: "nour.ibrahim@gmail.com",
    phone: "+20 115 567 8901",
    totalSpent: MOCK_PRODUCTS[4].price,
    totalOrders: 1,
    lastPurchase: new Date(Date.now() - 86400000 * 3).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 20).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-006",
    name: "Youssef Mahmoud",
    email: "y.mahmoud@gmail.com",
    phone: "+20 101 678 9012",
    totalSpent: MOCK_PRODUCTS[5].price * 3,
    totalOrders: 5,
    lastPurchase: new Date(Date.now() - 86400000 * 4).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 90).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-007",
    name: "Layla Adel",
    email: "layla.adel@hotmail.com",
    phone: "+20 122 789 0123",
    totalSpent: MOCK_PRODUCTS[11].price,
    totalOrders: 1,
    lastPurchase: new Date(Date.now() - 86400000 * 7).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    status: "Inactive",
  },
  {
    id: "CUS-008",
    name: "Karim Samir",
    email: "karim.s@gmail.com",
    phone: "+20 100 890 1234",
    totalSpent: 0,
    totalOrders: 1,
    lastPurchase: new Date(Date.now() - 86400000 * 5).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 50).toISOString(),
    status: "Inactive",
  },
  {
    id: "CUS-009",
    name: "Hana Mostafa",
    email: "hana.m@gmail.com",
    phone: "+20 111 901 2345",
    totalSpent: MOCK_PRODUCTS[7].price * 2,
    totalOrders: 2,
    lastPurchase: new Date(Date.now() - 86400000 * 10).toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 100).toISOString(),
    status: "Active",
  },
  {
    id: "CUS-010",
    name: "Tarek Nabil",
    email: "tarek.n@yahoo.com",
    phone: "+20 100 012 3456",
    totalSpent: MOCK_PRODUCTS[9].price + MOCK_PRODUCTS[10].price,
    totalOrders: 1,
    lastPurchase: new Date().toISOString(),
    joinedDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: "Active",
  },
];

// ─── Sales Data ──────────────────────────────────────────
const totalRevenue = MOCK_ORDERS.filter(
  (o) => o.paymentStatus === "Paid"
).reduce((sum, o) => sum + o.total, 0);

const todayOrders = MOCK_ORDERS.filter(
  (o) => new Date(o.date).toDateString() === new Date().toDateString()
);

const todayRevenue = todayOrders
  .filter((o) => o.paymentStatus === "Paid")
  .reduce((sum, o) => sum + o.total, 0);

export const SALES_DATA: SalesData = {
  today: {
    revenue: todayRevenue,
    orders: todayOrders.length,
    avgOrderValue: todayOrders.length > 0 ? todayRevenue / todayOrders.length : 0,
  },
  week: {
    revenue: totalRevenue * 0.35,
    orders: Math.floor(MOCK_ORDERS.length * 0.6),
    avgOrderValue: (totalRevenue * 0.35) / Math.floor(MOCK_ORDERS.length * 0.6),
  },
  month: {
    revenue: totalRevenue,
    orders: MOCK_ORDERS.length,
    avgOrderValue: totalRevenue / MOCK_ORDERS.length,
  },
  pendingOrdersCount: MOCK_ORDERS.filter(o => o.orderStatus === "New Order" || o.orderStatus === "Contacted").length,
  weeklyRevenueTarget: 50000,
  monthlyCustomersTarget: 40,
  monthlyProductsSoldTarget: 200,
  productsSoldThisMonth: 156,
  revenueChart: [
    { date: "Jun 1", revenue: 420, orders: 4 },
    { date: "Jun 2", revenue: 680, orders: 6 },
    { date: "Jun 3", revenue: 390, orders: 3 },
    { date: "Jun 4", revenue: 870, orders: 8 },
    { date: "Jun 5", revenue: 540, orders: 5 },
    { date: "Jun 6", revenue: todayRevenue, orders: todayOrders.length },
  ],
};